/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum HttpMethod {
  GET = 0,
  HEAD = 1,
  OPTIONS = 2,
  DELETE = 3,
  POST = 4,
  PUT = 5,
  PATCH = 6
}
export interface ClientConfig {
  auth?: Array<string>
  authBearer?: string
  headers?: Record<string, string>
  cookieStore?: boolean
  referer?: boolean
  proxy?: string
  timeout?: number
  impersonate?: string
  impersonateOs?: string
  followRedirects?: boolean
  maxRedirects?: number
  verify?: boolean
  caCertFile?: string
  httpsOnly?: boolean
  http2Only?: boolean
}
export declare class Response {
  readonly url: string
  readonly statusCode: number
  headers(): Record<string, string>
  cookies(): Record<string, string>
  text(): Promise<string>
  json(): Promise<any>
  content(): Promise<Buffer>
}
export declare class Client {
  constructor(config?: ClientConfig | undefined | null)
  request(method: HttpMethod, url: string, params?: Record<string, string> | undefined | null, headers?: Record<string, string> | undefined | null, cookies?: Record<string, string> | undefined | null, content?: Buffer | undefined | null, data?: Record<string, string> | undefined | null, json?: any | undefined | null, files?: Record<string, string> | undefined | null, auth?: Array<string> | undefined | null, authBearer?: string | undefined | null, timeout?: number | undefined | null): Promise<Response>
}
